version: '3.9'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'localhost'
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '8200:80'
      - '8201:443'
      - '8202:22'  # SSH port
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'